######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 21 16:57:54 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydlg.h widget.h
FORMS += mydlg.ui widget.ui
SOURCES += main.cpp mydlg.cpp widget.cpp
